### PR TITLE
Fix typo in the readme

### PR DESCRIPTION
**Pull request by rosner**
In my mind this makes more sense.

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

📝 Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by oguzhanunlu** [comment]
Thanks for the contribution @rosner ! Cherry-picked into [`v0.5.0`](https://github.com/snowplow/snowplow-mini/pull/159). Closing.

**Comment by oguzhanunlu** [comment]
Build fails due to incompatibility between Caddy and golang version, see #158 . This is going to be fixed in `v0.5.0` release.

**Comment by oguzhanunlu** [comment]
Closing the PR since @rosner hasn't signed CLA yet and `0.5.0` is getting ready for release.

**Pull request closed without merging**
